### ISSUE TITLE
AttributeError during the import of the module: `initialized module 'serpapi' has no attribute 'GoogleSearch' (most likely due to a circular import)` 

### ISSUE THREAD

**Issue by Ciroxxxx** [serpapi/google-search-results-python#42]
The first line of your code example:
from serpapi import GoogleSearch 
[here](https://serpapi.com/blog/using-google-maps-local-results-from-serpapi/#fullcode)
gives me
AttributeError: partially initialized module 'serpapi' has no attribute 'GoogleSearch' (most likely due to a circular import)

**Comment by dimitryzub** [comment]
Hey @Ciroxxxx 🙂

Not sure why this is happened to you. I assume that this error might occur _only_ when the relative import is used i.e.:

```
from .serpapi import GoogleSearch
``` 

instead of absolute `from serpapi import GoogleSearch` (which it is in this case).

____

Possibly try using a delay import (although it should work without it) which will import the modules at runtime instead of at compile time, like:

```python
def my_function():
    from serpapi import GoogleSearch

    # code that uses GoogleSearch here
```

____

The code provided from the blog post works as expected (just ran it on a newly created repl):

![image](https://user-images.githubusercontent.com/78694043/229710987-bc25c7f9-3384-4d92-a510-012ca50e0a3d.png)

**Comment by Ciroxxxx** [comment]
Hi @dimitryzub thank for your answer.
Yesterday I was on Mac and I had the issue.
I tested your code now on another computer, on Windows and it works.

Do you have any hint to test why on Mac it doesn't work?
Thank you

**Comment by dimitryzub** [comment]
@Ciroxxxx thank you for mentioning that you had this issue on Mac. Interesting.

Have you run the script on Mac with created virtual environment or `google-search-results` was installed globally? 

Virtual environment:

```bash
$ python<your_python_version> -m venv env 
$ source env/bin/activate
$ python<your_python_version> -m pip install google-search-results

# <your_python_version> - python3.10 for example
```

**Comment by Ciroxxxx** [comment]
I solved it!! 
It was a big mistake of mine, since I named the script from which I run your example code serpapi.py
and that caused of course the circular error.
Sorry if I bothered you....
